kind: Service
apiVersion: v1
metadata:
  name: scheduler-service
spec:
  type: NodePort
  selector:
    app: scheduler
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: scheduler-deployment
  labels:
    app: scheduler
spec:
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      volumes:
      - name: scheduler-opt
        hostPath:
          path: /opt/crond
      initContainers:
      - name: init-opt
        image: alpine
        command: ["mkdir"]
        args: ["-p", "/opt/crond/crontabs"]
        volumeMounts:
          - name: scheduler-opt
            mountPath: /opt/crond/
      containers:
      - name: crond
        image: pratikmallya/cronddocker
        imagePullPolicy: Always
        volumeMounts:
          - name: scheduler-opt
            mountPath: /opt/crond/
      - name: api
        image: pratikmallya/scheduler
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: scheduler-opt
            mountPath: /opt/crond/
